# Generated by Django 4.2.8 on 2023-12-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_cfdb_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolesRaisers',
        ),
    ]
